# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algorithm_tester.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x61lgorithm_tester.proto\"\x06\n\x04Null\"\'\n\tTimerange\x12\r\n\x05\x62\x65gin\x18\x01 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x02 \x01(\x03\"1\n\x04Test\x12\x16\n\x0e\x61lgorithm_name\x18\x01 \x02(\t\x12\x11\n\trun_count\x18\x02 \x02(\x05\"v\n\x03Job\x12\x0e\n\x06job_id\x18\x01 \x02(\t\x12\x13\n\x04test\x18\x02 \x01(\x0b\x32\x05.Test\x12\x1a\n\x06status\x18\x03 \x01(\x0e\x32\n.JobStatus\x12\r\n\x05start\x18\x04 \x01(\x03\x12\x0b\n\x03\x65nd\x18\x05 \x01(\x03\x12\x12\n\ncompletion\x18\x06 \x01(\x01\"\x1a\n\x05\x45ntry\x12\x11\n\x03job\x18\x01 \x02(\x0b\x32\x04.Job\"\x83\x01\n\x0bSearchQuery\x12\x1a\n\x06status\x18\x01 \x01(\x0e\x32\n.JobStatus\x12\x19\n\x05start\x18\x02 \x01(\x0b\x32\n.Timerange\x12\x17\n\x03\x65nd\x18\x03 \x01(\x0b\x32\n.Timerange\x12\x11\n\talgorithm\x18\x04 \x01(\t\x12\x11\n\trun_count\x18\x05 \x01(\x05*>\n\tJobStatus\x12\n\n\x06QUEUED\x10\x00\x12\x0b\n\x07RUNNING\x10\x01\x12\r\n\tCOMPLETED\x10\x02\x12\t\n\x05\x45RROR\x10\x03\x32\x43\n\nTimeTester\x12\x18\n\x07RunTest\x12\x05.Test\x1a\x04.Job\"\x00\x12\x1b\n\x0b\x43heckStatus\x12\x04.Job\x1a\x04.Job\"\x00\x32K\n\x0c\x45ntryService\x12\x19\n\x04List\x12\x05.Null\x1a\x06.Entry\"\x00\x30\x01\x12 \n\x04\x46ind\x12\x0c.SearchQuery\x1a\x06.Entry\"\x00\x30\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'algorithm_tester_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOBSTATUS._serialized_start=408
  _JOBSTATUS._serialized_end=470
  _NULL._serialized_start=26
  _NULL._serialized_end=32
  _TIMERANGE._serialized_start=34
  _TIMERANGE._serialized_end=73
  _TEST._serialized_start=75
  _TEST._serialized_end=124
  _JOB._serialized_start=126
  _JOB._serialized_end=244
  _ENTRY._serialized_start=246
  _ENTRY._serialized_end=272
  _SEARCHQUERY._serialized_start=275
  _SEARCHQUERY._serialized_end=406
  _TIMETESTER._serialized_start=472
  _TIMETESTER._serialized_end=539
  _ENTRYSERVICE._serialized_start=541
  _ENTRYSERVICE._serialized_end=616
# @@protoc_insertion_point(module_scope)
